# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: "*/30 7 * * *"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup:
  runs-on: ubuntu-latest
    steps: 
    - name: clean space
      run: |
        wget https://github.com/apache/flink/raw/master/tools/azure-pipelines/free_disk_space.sh
        chmod +x free_disk_space.sh
        sh free_disk_space.sh
        rm -rf "/usr/local/share/boost"
        rm -rf "$AGENT_TOOLSDIRECTORY"
        apt clean

  build:
    needs: cleanup
    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

   -  name: Setup build environment
      run: |
        df -h
        sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        pacman -Syyu --needed --noconfirm sudo git fakeroot binutils base-devel xmlto docbook-xsl inetutils bc pahole patchutils python-sphinx python-sphinx_rtd_theme graphviz imagemagick --noprogressbar
        useradd -p builderbob -c builderbob -m builderbob
        df -h
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        #git clone https://github.com/Aeolus-Linux/linux-tkg-noninteractive.git
        cd linux-tkg-noninteractive
        chmod +x free_disk_space.sh
        git init
        mkdir upstream
        cd upstream
        git clone https://github.com/Frogging-Family/linux-tkg.git
        rm ./linux-tkg/customization.cfg
        cd ..
        cp ./fileskept/customization.cfg ./upstream/linux-tkg/
        chown -R builderbob:builderbob ./upstream/
        chmod 777 -R ./upstream/
        cd upstream
        chmod 777 -R ./linux-tkg/
        cd linux-tkg
    - name: Build Kernel
      run: |
        su -c "makepkg -s" builderbob
    - name: Copy output and clean up repo
      run: |
        cd .. && cd ..
        rm -rf output
        mkdir output
        chmod -R 777 ./output/
        chown -R builderbob:builderbob ./output/
        cp ./upstream/linux-tkg/*.pkg.tar.zst ./output/
        rm -rf upstream
        git add *
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Update Package>
          skip-checks: true
      run: |
        # Hard-code user configuration
        cd linux-tkg-noninteractive
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
